"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import performance_tests.contracts.services.accounts.account_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UpdateAccountBalanceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BALANCE_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    balance: builtins.float
    account_id: builtins.str
    def __init__(
        self,
        *,
        balance: builtins.float = ...,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "balance", b"balance"]) -> None: ...

global___UpdateAccountBalanceRequest = UpdateAccountBalanceRequest

@typing.final
class UpdateAccountBalanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    @property
    def account(self) -> performance_tests.contracts.services.accounts.account_pb2.Account: ...
    def __init__(
        self,
        *,
        account: performance_tests.contracts.services.accounts.account_pb2.Account | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account"]) -> None: ...

global___UpdateAccountBalanceResponse = UpdateAccountBalanceResponse
